### ISSUE TITLE
Roadmap: New README

### ISSUE THREAD

**Issue by mluizaa00** [celesteoficial/java-library#45]
### Bungeecord

- [ ] AbstractBungeePlugin

**____________________________**

### Core

- [ ] Json
- [ ] ThreadingFactory
- [ ] Cooldown
- [ ] Registry, Inflexible, Lists
- [ ] All utilities classes

**____________________________**

### Spigot

- [ ] Menu
- [ ] EventWaiter
- [ ] ChatMonitor
- [ ] All utilities classes
